openapi: "3.0.0"
info:
  title: "Mes APIs"
  description: ""
  version: "0.0.1"

servers:
  - url: 'http://127.0.0.1:4010/'
    description: prism mock server

paths:
  $ref: "paths.yaml"

components:
  schemas:
    $ref: "schemas.yaml"