
openapi: "3.0.0"
info:
  title: "Tourny APIs"
  description: "API documentation for all APIs regarding the Tourny app."
  version: "0.0.1"
tags:
- name: Players
  description: ""

servers:
  - url: 'http://127.0.0.1:4010/'
    description: prism mock server

paths:
  $ref: "paths/index.yaml"

  # /tournaments/{id}/matches/{id}
  # /tournaments/{id}/matches/{id}/opponents --> lecture seule
  # /tournaments/{id}/matches/{id}/games --> lecture seule

  # /tournaments/{id}/matches/games --> écriture et déclenche le set des /opponents du match suivant


  # POST /tournaments/{id}/rank/{8}/matches


  # POST /tournaments/{id}/rank/{8}/matches

components:
  schemas:
    $ref: "schemas/index.yaml"